Mysql:
  Host: 127.0.0.1
  Port: 3306
  Username: root
  Password: 123456
  DBName: erinyes
  MaxOpenConns: 100
  MaxIdleConns: 10
Service:
  Port: ":8080"
IPMap:
  10.10.0.100: product-purchase-authorize-cc$e7463260e076
  10.10.0.101: product-purchase$9e0f115ee1ae
  10.10.0.99: product-purchase-get-price$92c34a1672c7
  10.10.0.102: product-purchase-publish$8789cd7f25d4
GatewayMap:
  ip5: true